### ISSUE TITLE
Random search for palettes doesn't work

### ISSUE THREAD

**Issue by flopp** [juangallostra/Colourlovers-API-wrapper#27]
## Steps to reproduce

Setup:

```
python3 -m venv .env
.env/bin/pip install --upgrade pip
.env/bin/pip install colourlovers
```

Then run `.env/bin/python script.py` with

```python
from colourlovers import clapi
cl = clapi.ColourLovers()

for type in ['new', 'top', 'random']:
    print(type)
    print(cl.search_palettes(request=type, numResults=1))
```

## Current behavior

This prints

```
new
[<colourlovers.data_containers.Palette object at 0x7f33644cad60>]
top
[<colourlovers.data_containers.Palette object at 0x7f3362fcec10>]
random
Traceback (most recent call last):
  File "./script.py", line 8, in <module>
    print(cl.search_palettes(request=type, numResults=1))
  File "./.env/lib/python3.8/site-packages/colourlovers/clapi.py", line 237, in _api_search
    processed_request = self.__process_optional_requests(search_type, **kwargs)
  File "./.env/lib/python3.8/site-packages/colourlovers/clapi.py", line 402, in __process_optional_requests
    del kwargs[valid_keyword]
KeyError: 'request'
```

So, `new` and `top` searches work, but `random` fails.

## Expected behavior

`cl.search_palettes(request="random", numResults=1)` should return a list containing one random `Palette` object.

**Comment by juangallostra** [comment]
@flopp I think this is happening because the type of request `random` does not accept parameters, it returns a single random object of the requested type. It is a limitation of the Colourlover's API and I haven't added any functionality on top of that. 

We could make it work by calling many times the `random` endpoint and storing the results of each call, but since this is just a wrapper I'm not sure it is a good idea to add many extra functionalities that are not supported by the API.

Can you try if the request without the `numResults` works?

From the API documentation:
![imagen](https://user-images.githubusercontent.com/9968427/87847244-e6441700-c8d6-11ea-8c88-0cf3f5fb9a94.png)

**Comment by juangallostra** [comment]
@flopp a part from that, I have to admit that the error message does not document well the error... 😅

**Comment by flopp** [comment]
I see the same behavior when omitting the `numResults` parameter:

```
from colourlovers import clapi
cl = clapi.ColourLovers()

for type in ['new', 'top', 'random']:
    print(type)
    print(cl.search_palettes(request=type))
```

=>

```
new
[<colourlovers.data_containers.Palette object at 0x7f48d703ec70>, <colourlovers.data_containers.Palette object at 0x7f48d703e370>, <colourlovers.data_containers.Palette object at 0x7f48d703e880>, <colourlovers.data_containers.Palette object at 0x7f48d703e940>, <colourlovers.data_containers.Palette object at 0x7f48d703e610>, <colourlovers.data_containers.Palette object at 0x7f48d703e820>, <colourlovers.data_containers.Palette object at 0x7f48d703e790>, <colourlovers.data_containers.Palette object at 0x7f48d703e910>, <colourlovers.data_containers.Palette object at 0x7f48d703eb80>, <colourlovers.data_containers.Palette object at 0x7f48d703ebb0>, <colourlovers.data_containers.Palette object at 0x7f48d703ebe0>, <colourlovers.data_containers.Palette object at 0x7f48d703edc0>, <colourlovers.data_containers.Palette object at 0x7f48d703ec10>, <colourlovers.data_containers.Palette object at 0x7f48d703eca0>, <colourlovers.data_containers.Palette object at 0x7f48d703ecd0>, <colourlovers.data_containers.Palette object at 0x7f48d703ed90>, <colourlovers.data_containers.Palette object at 0x7f48d703edf0>, <colourlovers.data_containers.Palette object at 0x7f48d703ed30>, <colourlovers.data_containers.Palette object at 0x7f48d703ed60>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e5b0>]
top
[<colourlovers.data_containers.Palette object at 0x7f48d5b3eaf0>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e790>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e910>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e820>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e850>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e880>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e970>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e9a0>, <colourlovers.data_containers.Palette object at 0x7f48d5b3e9d0>, <colourlovers.data_containers.Palette object at 0x7f48d5b3ea00>, <colourlovers.data_containers.Palette object at 0x7f48d5b3eac0>, <colourlovers.data_containers.Palette object at 0x7f48d5b3ea30>, <colourlovers.data_containers.Palette object at 0x7f48d5b3ea90>, <colourlovers.data_containers.Palette object at 0x7f48d5b3ea60>, <colourlovers.data_containers.Palette object at 0x7f48d5b3eb20>, <colourlovers.data_containers.Palette object at 0x7f48d5b3eb50>, <colourlovers.data_containers.Palette object at 0x7f48d5b3eb80>, <colourlovers.data_containers.Palette object at 0x7f48d5b3ebb0>, <colourlovers.data_containers.Palette object at 0x7f48d5b3ebe0>, <colourlovers.data_containers.Palette object at 0x7f48d5b3ec10>]
random
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    print(cl.search_palettes(request=type))
  File "./.env/lib/python3.8/site-packages/colourlovers/clapi.py", line 237, in _api_search
    processed_request = self.__process_optional_requests(search_type, **kwargs)
  File "./.env/lib/python3.8/site-packages/colourlovers/clapi.py", line 402, in __process_optional_requests
    del kwargs[valid_keyword]
KeyError: 'request'
